### Variables
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MGZmOGM4NGMwOGVjNjkyZGM0NmNlZmMiLCJpYXQiOjE2Mjc5NjMxMjcsImV4cCI6MTYyODMyMzEyN30.gJ93wisRC6xAbJXbn6T40RxACksuJSA2ThFS8KNWBVA
@course = { "name": "INF2045", "problems": ["51bb793aca2ab77a3200000d"] }

@courses = {"courses": "61072b46eeaac73f602e04b9", "userId": "60ff8c84c08ec692dc46cefc"}

### Get authenticated user given the token
GET  http://localhost:8000/api/course/create
x-auth-token: {{token}}

### Login user and get token
POST  http://localhost:8000/api/course/create
content-type: application/json

{{course}}

### Assign a new course to the user
POST  http://localhost:8000/api/course/assign
content-type: application/json
x-auth-token: {{token}}

{{courses}}