### Variables
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1Y2Q2ODMxZjFhY2I0ZjBiNjkxYzRlZjYiLCJpYXQiOjE1NTc1NjIxNDMsImV4cCI6MTU1NzkyMjE0M30.BP7n27AVY9MKTz1ViHMJWOVqQGMktJmT8AJWrZuQoP0
@course = { "name": "INF2045", "problems": ["51bb793aca2ab77a3200000d"] }

### Get authenticated user given the token
GET  http://localhost:8000/api/course/create
x-auth-token: {{token}}

### Login user and get token
POST  http://localhost:8000/api/course/create
content-type: application/json

{{course}}