### Variables
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1Y2Q2ODMxZjFhY2I0ZjBiNjkxYzRlZjYiLCJpYXQiOjE1NTc1NjIxNDMsImV4cCI6MTU1NzkyMjE0M30.BP7n27AVY9MKTz1ViHMJWOVqQGMktJmT8AJWrZuQoP0
@problem = { "question":"what is the best processor","title": "Processor PolyRisc","courses": ["61072b46eeaac73f602e04b9"], "type": "qcm", "answers": ["yes", "maybe"], "processor": "2" }

### Get authenticated user given the token
GET  http://localhost:8000/api/course/create
x-auth-token: {{token}}

### Login user and get token
POST  http://localhost:8081/api/problem/create
content-type: application/json

{{problem}}