### Variables
@user = { "email": "tesasdft1@polymtl.ca","matricule": "19245677", "password": "mael2015", "firstname": "admin", "lastname": "admin", "role": "ADMIN"}

### Register user given their email and password, returns the token upon successful registration
POST  http://localhost:3088/api/user/add
content-type: application/json

{{user}}